CREATE SCHEMA IF NOT EXISTS api;

CREATE ROLE anon NOLOGIN;
CREATE ROLE app_user NOLOGIN;

GRANT anon TO {{ env "PGUSER" }};
GRANT app_user TO {{ env "PGUSER" }};

GRANT USAGE ON SCHEMA api TO anon;
GRANT USAGE ON SCHEMA api TO app_user;
