services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: fulbo
      POSTGRES_USER: authenticator
      POSTGRES_PASSWORD: authenticator
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    command: postgres -c log_statement=all
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authenticator -d postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
  idp:
    image: quay.io/keycloak/keycloak:26.5.3
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      # This needs to be globally writeable with `chmod 777 data/keycloakdata`
      - ./data/keycloakdata:/opt/keycloak/data/h2
  migrate:
    image: ghcr.io/jackc/tern:v2.3.5
    profiles: [oneoff]
    environment:
      PGHOST: db
      PGPORT: "5432"
      PGDATABASE: fulbo
      PGUSER: authenticator
      PGPASSWORD: authenticator
    volumes:
      - ./db:/db
    working_dir: /db/migrations
    depends_on:
      db:
        condition: service_healthy
  schema:
    image: pgplex/pgschema:latest
    profiles: [oneoff]
    environment:
      PGHOST: db
      PGPORT: "5432"
      PGDATABASE: fulbo
      PGUSER: authenticator
      PGPASSWORD: authenticator
      PGAPPNAME: api
      PGSCHEMA_PLAN_HOST: db
      PGSCHEMA_PLAN_PORT: "5432"
      PGSCHEMA_PLAN_DB: pgschema_plan
      PGSCHEMA_PLAN_USER: authenticator
      PGSCHEMA_PLAN_PASSWORD: authenticator
    volumes:
      - ./db:/db
    working_dir: /db
    depends_on:
      db:
        condition: service_healthy
  postgrest:
    image: postgrest/postgrest:v14.5
    env_file: "postgrest.env.local"
    environment:
      PGRST_DB_URI: postgres://authenticator:authenticator@db:5432/fulbo
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_ROLE_CLAIM_KEY: .resource_access.fulbo.roles[0]
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  admin:
    image: adminer
    restart: always
    ports:
      - "5050:8080"
    depends_on:
      db:
        condition: service_healthy
  lgtm:
    image: grafana/otel-lgtm
    ports:
      - "3200:3000"   # Grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - lgtmdata:/data
  alloy:
    image: grafana/alloy
    ports:
      - "12347:12347" # Faro collector
    volumes:
      - ./deploy/alloy-local.alloy:/etc/alloy/config.alloy
    depends_on:
      - lgtm

volumes:
  pgdata:
  lgtmdata:
