\i schema/postgrest.sql
\i schema/auth.sql
\i schema/users.sql
\i schema/groups.sql
\i schema/players.sql
\i schema/matches.sql
\i schema/attendance.sql
\i schema/player_attributes.sql
\i schema/player_ratings.sql
\i schema/player_attribute_votes.sql
\i schema/player_vote_averages.sql
\i schema/match_teams.sql
\i schema/weekly_availability.sql
